require('dotenv').config();

const {
  AUTH_CONSTANTS,
  COMMON_CONSTANTS,
  ENVIRONMENTS
} = require('../constants');

// Default configuration values
const DEFAULTS = {
  PORT: 3000,
  JWT_SECRET: 'your-secret-key-change-in-production',
  DATA_DIR: './data',
  UPLOAD_DIR: './uploads',
  CORS_ORIGIN: '*'
};

module.exports = {
  // Server Configuration
  PORT: process.env.PORT || DEFAULTS.PORT,
  NODE_ENV: process.env.NODE_ENV || COMMON_CONSTANTS.ENVIRONMENTS.DEVELOPMENT,

  // JWT Configuration
  JWT_SECRET: process.env.JWT_SECRET || DEFAULTS.JWT_SECRET,
  JWT_EXPIRY: process.env.JWT_EXPIRY || AUTH_CONSTANTS.JWT.DEFAULT_EXPIRY,
  REFRESH_TOKEN_EXPIRY: process.env.REFRESH_TOKEN_EXPIRY || AUTH_CONSTANTS.JWT.DEFAULT_REFRESH_EXPIRY,

  // Storage Configuration
  DATA_DIR: process.env.DATA_DIR || DEFAULTS.DATA_DIR,
  UPLOAD_DIR: process.env.UPLOAD_DIR || DEFAULTS.UPLOAD_DIR,

  // File Upload Limits
  MAX_FILE_SIZE: COMMON_CONSTANTS.FILE_UPLOAD.MAX_SIZE,
  ALLOWED_FILE_TYPES: COMMON_CONSTANTS.FILE_UPLOAD.ALLOWED_MIME_TYPES,

  // CORS
  CORS_ORIGIN: process.env.CORS_ORIGIN || DEFAULTS.CORS_ORIGIN,

  // Bcrypt
  BCRYPT_ROUNDS: AUTH_CONSTANTS.PASSWORD.BCRYPT_ROUNDS,

  // Rate Limiting
  RATE_LIMIT_WINDOW_MS: parseInt(process.env.RATE_LIMIT_WINDOW_MS) || COMMON_CONSTANTS.RATE_LIMIT.WINDOW_MS,
  RATE_LIMIT_MAX_REQUESTS: parseInt(process.env.RATE_LIMIT_MAX_REQUESTS) || COMMON_CONSTANTS.RATE_LIMIT.MAX_REQUESTS,

  // Body Parser
  BODY_PARSER_JSON_LIMIT: COMMON_CONSTANTS.BODY_PARSER.JSON_LIMIT,
  BODY_PARSER_URLENCODED_LIMIT: COMMON_CONSTANTS.BODY_PARSER.URLENCODED_LIMIT
};
